@startuml

class Professeur

class Discipline

class Cours

class Etudiant

Etudiant "5..30" -- "*" Cours

diamond coursExistant

Professeur "1" -- coursExistant
Discipline "*" -- coursExistant
Cours "1" -- coursExistant

@enduml